// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3FwgDz78DWH0DP7MTPgtfKi-CvRVxfY4',
    appId: '1:797289849265:web:db95fe19a1542d0389dd90',
    messagingSenderId: '797289849265',
    projectId: 'travelexpense-6cfa2',
    authDomain: 'travelexpense-6cfa2.firebaseapp.com',
    storageBucket: 'travelexpense-6cfa2.firebasestorage.app',
    measurementId: 'G-SKRJ6LP37T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeOrLEDLhsrWH35F-VZ6AGhXlFDqBhE5o',
    appId: '1:797289849265:android:326f69573e73a7b189dd90',
    messagingSenderId: '797289849265',
    projectId: 'travelexpense-6cfa2',
    storageBucket: 'travelexpense-6cfa2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMVmW63HazbdEuRn_CuyaOTD2gi_WwxHo',
    appId: '1:797289849265:ios:158d70e0750ca93c89dd90',
    messagingSenderId: '797289849265',
    projectId: 'travelexpense-6cfa2',
    storageBucket: 'travelexpense-6cfa2.firebasestorage.app',
    iosBundleId: 'com.example.travelexpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMVmW63HazbdEuRn_CuyaOTD2gi_WwxHo',
    appId: '1:797289849265:ios:158d70e0750ca93c89dd90',
    messagingSenderId: '797289849265',
    projectId: 'travelexpense-6cfa2',
    storageBucket: 'travelexpense-6cfa2.firebasestorage.app',
    iosBundleId: 'com.example.travelexpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3FwgDz78DWH0DP7MTPgtfKi-CvRVxfY4',
    appId: '1:797289849265:web:ff221bde74d4136089dd90',
    messagingSenderId: '797289849265',
    projectId: 'travelexpense-6cfa2',
    authDomain: 'travelexpense-6cfa2.firebaseapp.com',
    storageBucket: 'travelexpense-6cfa2.firebasestorage.app',
    measurementId: 'G-3GWDM201ZJ',
  );
}
